---
- name: Copy nginx config file to webserver
  hosts: web
  become: true
  tasks:
    - name: Copy over example.internal.conf
      ansible.builtin.copy:
        src: ./example.internal.conf
        dest: /etc/nginx/conf.d/example.internal.conf
        mode: "0755"
        owner: root
      register: result

    - name: Create content directory
      ansible.builtin.file:
        path: /var/www/example.internal/html/
        state: directory
        mode: "0755"
        owner: root

    - name: Copy over index.html
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/example.internal/html/index.html
        mode: "0644"
        owner: root

    - name: Restart nginx to use the new config file
      when: result is changed
      ansible.builtin.service:
        name: nginx.service
        state: restarted
        enabled: true