---
- name: MariaDB-server Configuration
  hosts: db
  become: true
  vars:
    socket_location: /var/lib/mysql/mysql.sock
  tasks:
    - name: Ensure MariaDB-server & python3-PyMySQL is installed
      ansible.builtin.package:
        name: 
          - mariadb-server
          - python3-PyMySQL
        state: latest

    - name: Start MariaDB at boot
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true
    
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Print service facts
      ansible.builtin.debug:
        var: ansible_facts.services['mariadb.service']['state']

    - name: Create Database "webappdb"
      ansible.builtin.mysql_db:
        login_unix_socket: "{{ socket_location }}"
        check_implicit_admin: true
        name: webappdb
        state: present

    - name: Create Databseuser "webappuser"
      ansible.builtin.mysql_user:
        login_unix_socket: "{{ socket_location }}"
        check_implicit_admin: true
        name: webappuser
        password: secretpassword
        priv: "webappdb.*:ALL"
        state: present